# Generated by Django 5.2 on 2025-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_sports',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_brands',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Normal User'), ('ADMIN', 'Administrator')], default='USER', max_length=10),
        ),
    ]
